#x=input("1. Sayı;")
#y=input("2. Sayı;")
#print(type(x))
#print(type(y))
#print("Toplam:",x+y)
#print("Toplam:",int(x)+int(y))
pi =3.14
r=input("Yarıçap:")
print("Alan:",pi*float(r)*float(r))
print("Çevre:",2*pi*float(r))
